use_frameworks!

platform :ios, '13.0'

target 'SwiftAdditions_Example' do
  pod 'SwiftAdditions', :path => '../'

  target 'SwiftAdditions_ExampleTests' do
    inherit! :search_paths

    
  end
end
